trigger:
  branches:
    include: ['master']

variables:
  vswdbotLogin: vswdbot
  appiumVersion: 1.16.0
  basicOnly: false
  expoCLIVersion: latest
  nightlyBuild: false
  smokeTestDirectory: test/smoke
  - group: vswdbot-password

jobs:
  - job: Linux
    pool:
      name: 'React Native smoke tests - Linux'
    steps:
    - checkout: self
      clean: true
    - template: smoke-tests-common-validation.yml
