trigger:
  branches:
    include: ['master']

variables:
  vswdbotLogin: vswdbot
  appiumVersion: 1.16.0
  basicOnly: false
  expoCLIVersion: latest
  nightlyBuild: false
  smokeTestDirectory: test/smoke

jobs:
  - job: Linux
    variables:
    - group: 'vswdbot-password'
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      clean: true
    - template: smoke-tests-common-validation.yml
