trigger:
  branches:
    include: ['master']

jobs:
  - job: macOS
    pool:
      name: 'React Native smoke tests - macOS'
    steps:
    - checkout: self
      clean: true
    - template: smoke-tests-common-validation.yml
