trigger:
  - master
  - preview
pr:
  - master
  - preview

variables:
  vswdbotLogin: vswdbot
  appiumVersion: 1.18.2
  basicOnly: false
  expoCLIVersion: latest
  nightlyBuild: false
  smokeTestDirectory: test/smoke

jobs:
  - job: macOS
    pool:
      name: "React Native smoke tests - macOS"
    timeoutInMinutes: 90
    steps:
      - checkout: self
        clean: true
      - template: smoke-tests-common-validation.yml
