trigger:
  branches:
    include: ['master']

jobs:
  - job: Linux
    pool:
      name: 'React Native smoke tests - Linux'
    steps:
    - checkout:
      clean: true
    - template: smoke-tests-common-validation.yml
