/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.DateTimeCounts = require('./dateTimeCounts');
exports.ActiveDeviceCounts = require('./activeDeviceCounts');
exports.Model = require('./model');
exports.AnalyticsModels = require('./analyticsModels');
exports.AudienceSummary = require('./audienceSummary');
exports.Audience = require('./audience');
exports.AudienceDefinition = require('./audienceDefinition');
exports.AudienceDevicePropertiesListResult = require('./audienceDevicePropertiesListResult');
exports.AudienceDevicePropertyValuesListResult = require('./audienceDevicePropertyValuesListResult');
exports.AudienceListResult = require('./audienceListResult');
exports.AudienceTestResult = require('./audienceTestResult');
exports.CrashCounts = require('./crashCounts');
exports.DateTimePercentages = require('./dateTimePercentages');
exports.CrashFreeDevicePercentages = require('./crashFreeDevicePercentages');
exports.CrashGroupAndVersion = require('./crashGroupAndVersion');
exports.CrashGroupContainer = require('./crashGroupContainer');
exports.CrashGroupModel = require('./crashGroupModel');
exports.CrashGroupModels = require('./crashGroupModels');
exports.CrashGroupOperatingSystem = require('./crashGroupOperatingSystem');
exports.CrashGroupOperatingSystems = require('./crashGroupOperatingSystems');
exports.CrashOverall = require('./crashOverall');
exports.CrashesOverallItem = require('./crashesOverallItem');
exports.DateTimeDecimalCounts = require('./dateTimeDecimalCounts');
exports.Device = require('./device');
exports.ErrorCounts = require('./errorCounts');
exports.ErrorStackFrame = require('./errorStackFrame');
exports.ErrorGroup = require('./errorGroup');
exports.ErrorGroups = require('./errorGroups');
exports.Event = require('./event');
exports.EventCount = require('./eventCount');
exports.EventCountPerDevice = require('./eventCountPerDevice');
exports.EventCountPerSession = require('./eventCountPerSession');
exports.EventDeviceCount = require('./eventDeviceCount');
exports.EventProperties = require('./eventProperties');
exports.EventPropertyValue = require('./eventPropertyValue');
exports.EventPropertyValues = require('./eventPropertyValues');
exports.Events = require('./events');
exports.GenericLog = require('./genericLog');
exports.GenericLogContainer = require('./genericLogContainer');
exports.Release = require('./release');
exports.ReleaseWithDistributionGroup = require('./releaseWithDistributionGroup');
exports.GetReleasesContainer = require('./getReleasesContainer');
exports.Language = require('./language');
exports.Languages = require('./languages');
exports.LogFlowDevice = require('./logFlowDevice');
exports.LogFlowGenericLog = require('./logFlowGenericLog');
exports.LogFlowGenericLogContainer = require('./logFlowGenericLogContainer');
exports.LogFlowLog = require('./logFlowLog');
exports.LogFlowLogContainer = require('./logFlowLogContainer');
exports.OS = require('./os');
exports.OSes = require('./oSes');
exports.Place = require('./place');
exports.Places = require('./places');
exports.ReleaseCount = require('./releaseCount');
exports.ReleaseCounts = require('./releaseCounts');
exports.SessionDurationsDistributionDistributionItem = require('./sessionDurationsDistributionDistributionItem');
exports.SessionDurationsDistribution = require('./sessionDurationsDistribution');
exports.SessionsPerDeviceSessionsPerUserItem = require('./sessionsPerDeviceSessionsPerUserItem');
exports.SessionsPerDevice = require('./sessionsPerDevice');
exports.Version = require('./version');
exports.Versions = require('./versions');
exports.discriminators = {
  'LogFlowLog' : exports.LogFlowLog
};
