pr:
  - master
jobs:
- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
- template: common-validation.yml

- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
  - template: common-validation.yml

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - checkout: self
    clean: true
  - template: common-validation.yml