pr:
  branches:
    include: ["*"]

trigger:
  - none

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 20
    steps:
      - checkout: self
        clean: true
      - template: common-validation.yml
      - bash: npm run smoke-tests --verbose
        displayName: "Run smoke tests"
        env:
          DISPLAY: ":99.0"

  - job: Windows
    pool:
      vmImage: windows-latest
    timeoutInMinutes: 20
    steps:
      - checkout: self
        clean: true
      - template: common-validation.yml
      - bash: npm run smoke-tests --verbose
        displayName: "Run smoke tests"
        env:
          DISPLAY: ":99.0"

  - job: macOS
    pool:
      vmImage: macOS-latest
    timeoutInMinutes: 20
    steps:
      - checkout: self
        clean: true
      - template: common-validation.yml
      - bash: npm run smoke-tests --verbose
        displayName: "Run smoke tests"
        env:
          DISPLAY: ":99.0"
