pr:
  branches:
    include: ["*"]

variables:
  Codeql.Enabled: true

trigger:
  - none

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 20
    steps:
      - checkout: self
        clean: true
      - task: CodeQL3000Init@0
        displayName: CodeQL Initialize
      - template: common-validation.yml
      - task: CodeQL3000Finalize@0
        displayName: CodeQL Finalize

  - job: Windows
    pool:
      vmImage: windows-latest
    timeoutInMinutes: 20
    steps:
      - checkout: self
        clean: true
      - task: CodeQL3000Init@0
        displayName: CodeQL Initialize
      - template: common-validation.yml
      - task: CodeQL3000Finalize@0
        displayName: CodeQL Finalize

  - job: macOS
    pool:
      vmImage: macOS-latest
    timeoutInMinutes: 20
    steps:
      - checkout: self
        clean: true
      - task: CodeQL3000Init@0
        displayName: CodeQL Initialize
      - template: common-validation.yml
      - task: CodeQL3000Finalize@0
        displayName: CodeQL Finalize
