// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
import * as nls from "vscode-nls";
const localize = nls.loadMessageBundle();

export const ERROR_STRINGS = {
    "CommandFailed": localize("CommandFailed", "Error while executing command '{0}'"),
    "CommandFailedWithErrorCode": localize("CommandFailedWithErrorCode", "Command '{0}' failed with error code {1}"),
    "ExpectedIntegerValue": localize("ExpectedIntegerValue", "Expected an integer. Couldn't read {0}"),
    "PackagerStartFailed": localize("PackagerStartFailed", "Error while executing React Native Packager."),
    "IOSDeployNotFound": localize("IOSDeployNotFound", "Unable to find ios-deploy. Please make sure to install it globally('npm install -g ios-deploy')"),
    "DeviceNotPluggedIn": localize("DeviceNotPluggedIn", "Unable to mount developer disk image."),
    "DeveloperDiskImgNotMountable": localize("DeveloperDiskImgNotMountable", "Unable to mount developer disk image."),
    "UnableToLaunchApplication": localize("UnableToLaunchApplication", "Unable to launch application."),
    "ApplicationLaunchTimedOut": localize("ApplicationLaunchTimedOut", "Timeout launching application. Is the device locked?"),
    "IOSSimulatorNotLaunchable": localize("IOSSimulatorNotLaunchable", "Unable to launch iOS simulator. Try specifying a different target."),
    "OpnPackagerLocationNotFound": localize("OpnPackagerLocationNotFound", "Opn package location not found"),
    "PackageNotFound": localize("PackageNotFound", "Attempting to find package {0} failed with error: {1}"),
    "PlatformNotSupported": localize("PlatformNotSupported", "Platform '{0}' is not supported on host platform: {1}"),
    "ProjectVersionNotParsable": localize("ProjectVersionNotParsable", "Couldn't parse the version component of the package at {0}: version = {1}"),
    "ProjectVersionUnsupported": localize("ProjectVersionUnsupported", "Project version = {0}"),
    "ProjectVersionNotReadable": localize("ProjectVersionNotReadable", "Unable to read version = {0}"),
    "TelemetryInitializationFailed": localize("TelemetryInitializationFailed", "{0}. Couldn't initialize telemetry"),
    "ExtensionActivationFailed": localize("ExtensionActivationFailed", "Failed to activate the React Native Tools extension"),
    "DebuggerStubLauncherFailed": localize("DebuggerStubLauncherFailed", "Failed to setup the stub launcher for the debugger"),
    "IntellisenseSetupFailed": localize("IntellisenseSetupFailed", "Failed to setup IntelliSense"),
    "NodeDebuggerConfigurationFailed": localize("NodeDebuggerConfigurationFailed", "Failed to configure the node debugger location for the debugger"),
    "FailedToStopPackagerOnExit": localize("FailedToStopPackagerOnExit", "Failed to stop the packager while closing React Native Tools"),
    "FailedToRunOnAndroid": localize("FailedToRunOnAndroid", "Failed to run the application in Android"),
    "FailedToRunOnIos": localize("FailedToRunOnIos", "Failed to run the application in iOS"),
    "FailedToRunExponent": localize("FailedToRunExponent", "Failed to run the application in Exponent"),
    "FailedToPublishToExpHost": localize("FailedToRunExponent", "Failed to publish the application to Exponent"),
    "FailedToStartPackager": localize("FailedToStartPackager", "Failed to start the React Native packager"),
    "FailedToStopPackager": localize("FailedToStopPackager", "Failed to stop the React Native packager"),
    "FailedToRestartPackager": localize("FailedToRestartPackager", "Failed to restart the React Native packager"),
    "DebuggingFailed": localize("DebuggingFailed", "Cannot debug application"),
    "DebuggingFailedInNodeWrapper": localize("DebuggingFailedInNodeWrapper", "Cannot debug application due to an error in the internal Node Debugger"),
    "RNTempFolderDeletionFailed": localize("RNTempFolderDeletionFailed", "Couldn't delete the temporary folder {0}"),
    "CouldNotFindLocationOfNodeDebugger": localize("CouldNotFindLocationOfNodeDebugger", "Couldn't find the location of the node-debugger extension"),
    "PackagerRunningInDifferentPort": localize("PackagerRunningInDifferentPort", "A packager cannot be started on port {0} because a packager process is already running on port {1}"),
    "ErrorWhileProcessingMessageInIPMSServer": localize("ErrorWhileProcessingMessageInIPMSServer", "An error ocurred while handling message: {0}"),
    "ErrorNoPipeFound": localize("ErrorNoPipeFound", "Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?"),
};
