/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.DeviceConfigurationImage = require('./deviceConfigurationImage');
exports.DeviceDimensions = require('./deviceDimensions');
exports.DeviceResolution = require('./deviceResolution');
exports.DeviceScreenSize = require('./deviceScreenSize');
exports.DeviceCpu = require('./deviceCpu');
exports.DeviceMemory = require('./deviceMemory');
exports.DeviceFrameDefinition = require('./deviceFrameDefinition');
exports.DeviceFrame = require('./deviceFrame');
exports.DeviceModel = require('./deviceModel');
exports.DeviceConfiguration = require('./deviceConfiguration');
exports.DeviceList = require('./deviceList');
exports.DeviceSelection = require('./deviceSelection');
exports.DeviceSetOwner = require('./deviceSetOwner');
exports.DeviceSetConfigurationImage = require('./deviceSetConfigurationImage');
exports.DeviceSetModel = require('./deviceSetModel');
exports.DeviceSetConfiguration = require('./deviceSetConfiguration');
exports.DeviceSet = require('./deviceSet');
exports.DeviceSetUpdate = require('./deviceSetUpdate');
exports.Tier = require('./tier');
exports.Subscription = require('./subscription');
exports.TestCloudFileHash = require('./testCloudFileHash');
exports.TestCloudFileHashDeprecated = require('./testCloudFileHashDeprecated');
exports.TestCloudHashUploadStatus = require('./testCloudHashUploadStatus');
exports.TestCloudFileHashResponse = require('./testCloudFileHashResponse');
exports.TestCloudStartTestRunOptions = require('./testCloudStartTestRunOptions');
exports.TestCloudStartTestRunResult = require('./testCloudStartTestRunResult');
exports.TestReportStats = require('./testReportStats');
exports.TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem = require('./testReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem');
exports.TestReportFeaturesItemTestsItemRunsItemStepsItem = require('./testReportFeaturesItemTestsItemRunsItemStepsItem');
exports.TestReportFeaturesItemTestsItemRunsItem = require('./testReportFeaturesItemTestsItemRunsItem');
exports.TestReportFeaturesItemTestsItem = require('./testReportFeaturesItemTestsItem');
exports.TestReportFeaturesItem = require('./testReportFeaturesItem');
exports.TestReportDeviceLogsItem = require('./testReportDeviceLogsItem');
exports.TestReport = require('./testReport');
exports.TestRunStatistics = require('./testRunStatistics');
exports.TestRun = require('./testRun');
exports.TestRunState = require('./testRunState');
exports.TestRunSummary = require('./testRunSummary');
exports.TestSeries = require('./testSeries');
exports.TestSeriesName = require('./testSeriesName');
