// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.


import {FileSystem} from "./utils/node/fileSystem";
import {Package} from "./utils/node/package";
import * as path from "path";
import * as vscode from "vscode";

import {ReactNativeCommandExecutor} from "./utils/reactNativeCommandExecutor";

export function activate(context: vscode.ExtensionContext): void {
    let currentPackage = new Package(vscode.workspace.rootPath);
     currentPackage.dependencies().then(dependencies => {
        if (dependencies && dependencies["react-native"]) {
            // Looks like a react native project: Set it up for debugging
            setupReactNativeDebugger();

            let reactNativeCommandExecutor = new ReactNativeCommandExecutor(vscode.workspace.rootPath);

            context.subscriptions.push(vscode.commands.registerCommand("reactNative.runAndroid",
            () => reactNativeCommandExecutor.executeReactNativeCommand("run-android")));
            context.subscriptions.push(vscode.commands.registerCommand("reactNative.runIos",
            () => reactNativeCommandExecutor.executeReactNativeCommand("run-ios")));
            context.subscriptions.push(vscode.commands.registerCommand("reactNative.startPackager",
            () => reactNativeCommandExecutor.startPackager()));
            context.subscriptions.push(vscode.commands.registerCommand("reactNative.stopPackager",
            () => reactNativeCommandExecutor.stopPackager()));
        }
    }).catch(() => { });
}

function setupReactNativeDebugger(): void {
    let launcherPath = require.resolve("./debugger/launcher");
    const extensionVersionNumber = require("../package.json").version;

    let debuggerEntryCode =
            `// This file is automatically generated. version:${extensionVersionNumber}
try {
    var path = require("path");
    var Launcher = require(${JSON.stringify(launcherPath)}).Launcher;
    new Launcher(path.resolve(__dirname, "..")).launch();
} catch (e) {
    throw new Error("Unable to launch application. Try deleting .vscode/launchReactNative.js and restarting vscode.");
}`;
    let vscodeFolder = path.join(vscode.workspace.rootPath, ".vscode");
    let debugStub = path.join(vscodeFolder, "launchReactNative.js");

    let fsUtil = new FileSystem();

    fsUtil.ensureDirectory(vscodeFolder).then(() => {
        fsUtil.ensureFileWithContents(debugStub, debuggerEntryCode);
    }).catch((err: Error) => {
        vscode.window.showErrorMessage(err.message);
    });
}